# Generated by Django 3.2.7 on 2021-09-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0002_rename_username_profile_user'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.CharField(default='abc', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='PENDING', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('submitted_by', 'assignment')},
        ),
    ]
