# Generated by Django 3.2.7 on 2021-09-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userName',
            new_name='user',
        ),
    ]
